language: node_js
node_js:
  - "0.10"


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - npm cache clean
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install -g bower
  - bower install


